Repository 5G-MAG/rt-5gms-application-function, pull requests merged in 2024-01, with the labels that each got.

#116 Add cmake and pyOpenSSL as dependencies in README.md
  README.md
Labels: documentation

#117 Feature/cicd clean
  .github/workflows/build.yml
Labels: CI/CD

#119 Enhancement: M1 session tool: policy templates operations
  tools/python3/lib/rt_m1_client/types.py
  tools/python3/m1_session_cli.py
Labels: enhancement
